[package]
edition = "2021"
name = "can2040_rs"
version = "0.1.0"
license = "MIT OR Apache-2.0"

[build-dependencies]
bindgen = "0.71.1"

[profile.release]
debug = 2

[profile.dev]
lto = true
opt-level = "z"
